### ISSUE TITLE
Minimal Excel example

### ISSUE THREAD

**Issue by Freymaurer** [plegerer/excelAddInContDev#1]
Hey man, i just saw you are using the office fable package. Awesome! As i belive you are propably the first person except for me to use it, i wanted to get in contact with you, if the documentation is sufficient to set up and use the package.

Let me know what you think!

**Comment by plegerer** [comment]
Hi, 
well, I struggled quite a lot, but this is more due to the fact that I am currently transitioning from VBA to Webaddins, with little to no background in javascript nor F#.
Nevertheless, I think the documention is fine, it kind of fully conveys the concept (initializing, working with promises, etc.). The code sample are a bit advanced though. What eventually got me going was copying code from your other project (SAFE-MinExcel). There, the Excel-Interop-Section is very concise and eas to understand.

But your work is so helpfull and you seem to be only one out there providing ressources for writing webaddins in F#. So thanks a lot for making it available.

Regards, Paul

**Comment by Freymaurer** [comment]
Thanks for the feedback! I linked the SAFE-MinExcel repo on the office-fable repo, so it's easier to find from there. 

If you find any things, which might need some extra documenation, please go ahead and tell me. I too have still a lot of things to learn regarding excel add-ins 😄
